name: Docker Build & Deploy on Release

on:
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:$VERSION \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:latest -f ./Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:$VERSION
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_NODE_APP_HOST }}
          username: ${{ secrets.MY_NODE_APP_USER }}
          key: ${{ secrets.MY_NODE_APP_KEY }}
          port: ${{ secrets.MY_NODE_APP_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:latest
            docker rm -f my-node-app || true
            docker image prune -f
            docker run -d --name my-node-app -p 443:443 -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/node-app-sample:latest
