name: Release and Deploy My Node App

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.GH_PAT }}

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Auto-approve and merge release PR
        if: steps.release.outputs.release_created != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          echo "Looking for open release PRs by github-actions[bot]..."
          PR_NUMBER=$(gh pr list --author "github-actions[bot]" --state open --json number --jq '.[0].number')
          echo "Found PR #$PR_NUMBER"
          if [ -n "$PR_NUMBER" ]; then
            echo "Approving PR #$PR_NUMBER..."
            gh pr review "$PR_NUMBER" --approve
            echo "Merging PR #$PR_NUMBER..."
            gh pr merge "$PR_NUMBER" --merge --admin
          else
            echo "No open release PR found."
          fi

  deploy:
    needs: release
    if: needs.release.outputs.release_created == 'true' # Only deploy on new release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_NODE_APP_HOST }}
          username: ${{ secrets.MY_NODE_APP_USER }}
          key: ${{ secrets.MY_NODE_APP_KEY }}
          port: ${{ secrets.MY_NODE_APP_PORT }}
          script: |
            set -e
            echo "Connecting to EC2 Instance..."
            cd /home/ubuntu/my-node-app || exit 1
            echo "Current Directory: $(pwd)"
            echo "Node Version: $(node -v)"
            echo "Git Status Before Pull:"
            git status || exit 1
            git pull origin main || exit 1
            echo "Installing required packages..."
            npm install
            echo "Restarting application using PM2..."
            pm2 restart my-node-app || pm2 start index.js --name my-node-app
            pm2 save
            echo "Deployment Completed Successfully ✅"
